name: fuel_manager
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.7+2
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  google_sign_in: ^5.4.0
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  dartz: ^0.10.1
  location: ^4.4.0
  google_maps_flutter: ^2.1.8
  intl: ^0.17.0
  geocoder2: ^1.1.2
  geolocator: ^9.0.0
  ionicons: ^0.1.2
  dynamic_color: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  triple_test: ^1.0.0
  modular_test: ^2.0.0
  flutter_launcher_icons: ^0.9.3

objectbox:
  output_dir: database

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"

vars: 
    clean: flutter clean
    pubget: flutter pub get
    runner: flutter pub run build_runner
    runn: flutter pub run

scripts: 
    clean: $clean & $pubget
    build: $runner build
    icon: $runn flutter_launcher_icons:main

