// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZGO8YNOiBj9nZ3w7ns2lGna5kav-A_zY',
    appId: '1:1007362438499:web:d033220e3fa9ec3042cf56',
    messagingSenderId: '1007362438499',
    projectId: 'fuel-manager-full',
    authDomain: 'fuel-manager-full.firebaseapp.com',
    storageBucket: 'fuel-manager-full.appspot.com',
    measurementId: 'G-FR5DHE9R99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjReKkMIBRCmIUUh1srI1eE8yb4eXl3bg',
    appId: '1:1007362438499:android:56cc1c02e0005ad442cf56',
    messagingSenderId: '1007362438499',
    projectId: 'fuel-manager-full',
    storageBucket: 'fuel-manager-full.appspot.com',
  );
}
